# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-13 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
    ]
